# Auto-generated by .github/workflows/homebrew-tap.yml — do not hand-edit.
# Source template: packages/homebrew-tap/pythinker-code.rb.tmpl
class PythinkerCode < Formula
  desc "Terminal-native review-first AI engineering agent"
  homepage "https://pythinker.com"
  version "0.45.0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/Pythoughts-labs/pythinker-code/releases/download/v0.45.0/pythinker-0.45.0-aarch64-apple-darwin-onedir.tar.gz"
      sha256 "eaaa22d1376f5b5c723edfed2767cb0af6bbb41f82826f04933a4524346d0e90"
    end

    on_intel do
      url "https://github.com/Pythoughts-labs/pythinker-code/releases/download/v0.45.0/pythinker-0.45.0-x86_64-apple-darwin-onedir.tar.gz"
      sha256 "3ea63b01e84a9a835668071ef1ac6657575f8913abd06d37c77ad6b09e7282d9"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/Pythoughts-labs/pythinker-code/releases/download/v0.45.0/pythinker-0.45.0-aarch64-unknown-linux-gnu-onedir.tar.gz"
      sha256 "1264b143c64b4c2a61f9da4556adb7ab21640e6f0084a781b24ee4e56592ec4b"
    end

    on_intel do
      url "https://github.com/Pythoughts-labs/pythinker-code/releases/download/v0.45.0/pythinker-0.45.0-x86_64-unknown-linux-gnu-onedir.tar.gz"
      sha256 "21afb200b95e5f4e6a2aca8a9b9c9f33f0c50a59f5ce3bc5a9df9fc64cf11e13"
    end
  end

  def install
    # Onedir PyInstaller build: a "pythinker" launcher next to an "_internal"
    # directory. Homebrew chdirs into the tarball's single "pythinker/" root,
    # so Dir["*"] is the launcher plus _internal. Install the whole tree into
    # libexec and put an exec wrapper on PATH so the launcher resolves
    # _internal next to its real location.
    libexec.install Dir["*"]
    (libexec/".pythinker-native").write "pythinker-native-build\n"
    bin.write_exec_script libexec/"pythinker"
  end

  def caveats
    # Static settled frame of the curl/PowerShell installers' "Tetris" logo
    # (install.sh / install.ps1). Homebrew renders caveats as plain text, so
    # this is the uncoloured robot-head. The squiggly heredoc strips the common
    # leading indent, so the art sits one column left of the curl banner.
    <<~EOS

            ●
            │
        ▛▀▀▀▀▀▀▀▜
       ◖█ ◉   ◉ █◗
        ▙▄▄▄≡▄▄▄▟

        pythinker code · your next CLI agent
    EOS
  end

  test do
    assert_path_exists libexec/".pythinker-native"
    assert_match version.to_s, shell_output("#{bin}/pythinker --version")
  end
end
