# Auto-generated by .github/workflows/homebrew-tap.yml — do not hand-edit.
# Source template: packages/homebrew-tap/pythinker-code.rb.tmpl
class PythinkerCode < Formula
  desc "Terminal-native review-first AI engineering agent"
  homepage "https://pythinker.com"
  version "0.19.0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/mohamed-elkholy95/Pythinker-Code/releases/download/v0.19.0/pythinker-0.19.0-aarch64-apple-darwin.tar.gz"
      sha256 "e2b29e1cc43733a92906d532c79e846f019893d77c4c55330987fe0d3859991b"
    end

    on_intel do
      url "https://github.com/mohamed-elkholy95/Pythinker-Code/releases/download/v0.19.0/pythinker-0.19.0-x86_64-apple-darwin.tar.gz"
      sha256 "4eff15045b4d1beb2d216b558240d66fbc6b16c421b26286362da80ccdbf3f8b"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/mohamed-elkholy95/Pythinker-Code/releases/download/v0.19.0/pythinker-0.19.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "2b008406e729308c942ae5a974e48ab0e51c7732758aa3c170de2125803c4405"
    end

    on_intel do
      url "https://github.com/mohamed-elkholy95/Pythinker-Code/releases/download/v0.19.0/pythinker-0.19.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "47333812e0465ad9a87d7f796a3f137b9dc7b974cb015d7a0342cf26b3526eeb"
    end
  end

  def install
    libexec.install "pythinker"
    (libexec/".pythinker-native").write "pythinker-native-build\n"
    bin.write_exec_script libexec/"pythinker"
  end

  test do
    assert_path_exists libexec/".pythinker-native"
    assert_match version.to_s, shell_output("#{bin}/pythinker --version")
  end
end
